import { NextResponse } from 'next/server';
import { pendingOpportunities,settleOpportunity } from '../../../../lib/db';
import { footballRequest,getFixturePlayers,type FixturePlayersTeam,type FootballFixture } from '../../../../lib/football';
import { requiredCount } from '../../../../lib/stat-model';
export const dynamic='force-dynamic';export const maxDuration=300;
const FINAL_STATUSES=new Set(['FT','AET','PEN']);const MAX_FIXTURES_PER_RUN=3;
function norm(s:string){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim()}
function same(a:string,b:string){const x=norm(a),y=norm(b);if(!x||!y)return false;if(x===y)return true;const xa=x.split(' '),ya=y.split(' '),xs=xa.at(-1),ys=ya.at(-1);if(!xs||!ys||xs.length<4||xs!==ys)return false;const xi=xa[0]?.[0],yi=ya[0]?.[0];return !xi||!yi||xi===yi}
function actualValue(teams:FixturePlayersTeam[],name:string,market:string){for(const team of teams){const p=team.players?.find(x=>same(x.player.name,name));const s=p?.statistics?.[0];if(!s)continue;if(market==='player_shots')return s.shots?.total??null;if(market==='player_shots_on_target')return s.shots?.on??null;if(market==='goalie_saves')return s.goals?.saves??null;if(market==='player_cards')return(s.cards?.yellow??0)+(s.cards?.red??0);if(market==='anytime_goal_scorer')return s.goals?.total??0;if(market==='goal_or_assist')return(s.goals?.total??0)+(s.goals?.assists??0)}return null}
export async function GET(request:Request){const secret=process.env.CRON_SECRET;if(secret&&request.headers.get('authorization')!==`Bearer ${secret}`)return NextResponse.json({ok:false,error:'Unauthorized'},{status:401});const pending=Array.from(await pendingOpportunities(60)) as any[];let settled=0,skipped=0,unfinished=0;const playerCache=new Map<number,FixturePlayersTeam[]>(),statusCache=new Map<number,string>();const fixtureIds=[...new Set(pending.map(o=>Number(o.fixture_id)).filter(Number.isFinite))].slice(0,MAX_FIXTURES_PER_RUN);for(const fixtureId of fixtureIds){try{const fixtureData=await footballRequest<{response:FootballFixture[]}>(`/fixtures?id=${fixtureId}`,300);const status=fixtureData.response?.[0]?.fixture?.status?.short??'UNKNOWN';statusCache.set(fixtureId,status);if(!FINAL_STATUSES.has(status)){unfinished++;continue}const data=await getFixturePlayers(fixtureId);playerCache.set(fixtureId,data.response??[])}catch{skipped++}}
for(const o of pending){const fixtureId=Number(o.fixture_id);if(!fixtureIds.includes(fixtureId))continue;if(!FINAL_STATUSES.has(statusCache.get(fixtureId)??''))continue;try{const teams=playerCache.get(fixtureId);if(!teams){skipped++;continue}const value=actualValue(teams,String(o.player??''),String(o.market));if(value===null){skipped++;continue}const line=Number(o.line??0.5),needed=(o.market==='anytime_goal_scorer'||o.market==='goal_or_assist')?1:requiredCount(line);await settleOpportunity(Number(o.id),value>=needed?'WIN':'LOSS',value);settled++}catch{skipped++}}
return NextResponse.json({ok:true,pendingChecked:pending.length,fixturesChecked:fixtureIds.length,maxFixturesPerRun:MAX_FIXTURES_PER_RUN,settled,unfinished,skipped,at:new Date().toISOString()})}
