import { NextResponse } from 'next/server';
import { pendingOpportunities,settleOpportunity } from '../../../../lib/db';
import { getFixturePlayers,type FixturePlayersTeam } from '../../../../lib/football';
import { requiredCount } from '../../../../lib/stat-model';
export const dynamic='force-dynamic';export const maxDuration=300;
function norm(s:string){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim()}
function same(a:string,b:string){const x=norm(a),y=norm(b);if(x===y)return true;const xs=x.split(' ').at(-1),ys=y.split(' ').at(-1);return Boolean(xs&&ys&&xs.length>=4&&xs===ys)}
function actualValue(teams:FixturePlayersTeam[],name:string,market:string){for(const team of teams){const p=team.players?.find(x=>same(x.player.name,name));const s=p?.statistics?.[0];if(!s)continue;if(market==='player_shots')return s.shots?.total??null;if(market==='player_shots_on_target')return s.shots?.on??null;if(market==='goalie_saves')return s.goals?.saves??null;if(market==='player_cards')return(s.cards?.yellow??0)+(s.cards?.red??0);if(market==='anytime_goal_scorer')return s.goals?.total??0;if(market==='goal_or_assist')return(s.goals?.total??0)+(s.goals?.assists??0)}return null}
export async function GET(request:Request){const secret=process.env.CRON_SECRET;if(secret&&request.headers.get('authorization')!==`Bearer ${secret}`)return NextResponse.json({ok:false,error:'Unauthorized'},{status:401});const pending=Array.from(await pendingOpportunities(60)) as any[];let settled=0,skipped=0;const cache=new Map<number,FixturePlayersTeam[]>();for(const o of pending){try{const fixtureId=Number(o.fixture_id);if(!cache.has(fixtureId)){const data=await getFixturePlayers(fixtureId);cache.set(fixtureId,data.response??[])}const value=actualValue(cache.get(fixtureId)!,String(o.player??''),String(o.market));if(value===null){skipped++;continue}const line=Number(o.line??0.5);const needed=(o.market==='anytime_goal_scorer'||o.market==='goal_or_assist')?1:requiredCount(line);await settleOpportunity(Number(o.id),value>=needed?'WIN':'LOSS',value);settled++}catch{skipped++}}return NextResponse.json({ok:true,pendingChecked:pending.length,settled,skipped,at:new Date().toISOString()})}
