import { NextResponse } from 'next/server';
import { getUpcomingMarketFeeds } from '../../../../lib/live-markets';
import { getPropLineSports } from '../../../../lib/propline';
import { footballRequest, type FootballFixture } from '../../../../lib/football';
import { evaluatePrices } from '../../../../lib/opportunity-engine';
import { ensureEarlyMarketTable,saveOpportunity,saveScan,trackEarlyMarket } from '../../../../lib/db';
export const dynamic='force-dynamic';export const maxDuration=300;
const FALLBACK_SPORTS=['soccer_epl','soccer_argentina_primera','soccer_uefa_champions_league'];
const WANTED=/(epl|premier|argentina|bundesliga|germany|la_liga|laliga|spain|serie_a|italy|ligue_1|france|champions|europa|copa)/i;
const DISCOVERY_HOURS=168;const DEEP_ANALYSIS_HOURS=24;const EARLY_ANALYSIS_HOURS=168;
const fixtureCache=new Map<string,FootballFixture[]>();
async function activeSports(){try{const all=await getPropLineSports();const selected=all.filter(s=>s.active&&s.key.startsWith('soccer_')&&WANTED.test(`${s.key} ${s.title}`)).map(s=>s.key);return selected.length?selected.slice(0,12):FALLBACK_SPORTS}catch{return FALLBACK_SPORTS}}
async function candidateFixtures(commenceTime?:string){if(!commenceTime)return[];const day=new Date(commenceTime).toISOString().slice(0,10);if(fixtureCache.has(day))return fixtureCache.get(day)!;const data=await footballRequest<{response:FootballFixture[]}>(`/fixtures?date=${day}&timezone=America%2FArgentina%2FBuenos_Aires`,21600);const fixtures=data.response??[];fixtureCache.set(day,fixtures);return fixtures}
function hoursUntil(value?:string|null){if(!value)return Infinity;return (Date.parse(value)-Date.now())/3600000}
export async function GET(request:Request){const secret=process.env.CRON_SECRET;if(secret&&request.headers.get('authorization')!==`Bearer ${secret}`)return NextResponse.json({ok:false,error:'Unauthorized'},{status:401});const startedAt=new Date().toISOString(),scans:any[]=[];let deepAnalysisUsed=false,earlyAnalysisUsed=false;await ensureEarlyMarketTable();const sports=await activeSports();
 for(const sport of sports){try{const feeds=await getUpcomingMarketFeeds(sport,4,20,DISCOVERY_HOURS);if(!feeds.length){const scanId=await saveScan({startedAt,sport,event:null,bookmakers:0,bet365Available:false,prices:0});scans.push({sport,scanId,persisted:true,reason:'No event inside discovery horizon'});continue}
  for(const feed of feeds){const event={id:String(feed.event.id),home_team:feed.event.home_team??null,away_team:feed.event.away_team??null,commence_time:feed.event.commence_time??null};const scanId=await saveScan({startedAt,sport,event,bookmakers:feed.bookmakers.length,bet365Available:feed.bet365Available,prices:feed.prices.length});let tracked=0;for(const p of feed.prices){await trackEarlyMarket(sport,event,p);tracked++}let evaluation:any=null,saved=0;const h=hoursUntil(event.commence_time),nearKickoff=h<=DEEP_ANALYSIS_HOURS&&h>=-0.5,earlyWindow=h<=EARLY_ANALYSIS_HOURS&&h>DEEP_ANALYSIS_HOURS;
   const shouldAnalyze=(!deepAnalysisUsed&&nearKickoff)||(!earlyAnalysisUsed&&earlyWindow);if(shouldAnalyze&&feed.prices.length&&process.env.FOOTBALL_API_KEY){if(nearKickoff)deepAnalysisUsed=true;else earlyAnalysisUsed=true;const fixtures=await candidateFixtures(event.commence_time??undefined);evaluation=await evaluatePrices(event,feed.prices,fixtures);const publishable=(evaluation.opportunities??[]).filter((o:any)=>o.decision?.status!=='SIN MODELO'&&o.decision?.status!=='DESCARTAR'&&o.sampleSize>=3);for(const o of publishable){await saveOpportunity(scanId,sport,event,o);saved++}}
   scans.push({sport,scanId,event,bookmakers:feed.bookmakers.length,bet365Available:feed.bet365Available,prices:feed.prices.length,earlyPricesTracked:tracked,fixtureMatched:Boolean(evaluation?.matched),lineupConfirmed:Boolean(evaluation?.lineupConfirmed),analysis:nearKickoff&&evaluation?'deep':earlyWindow&&evaluation?'early':false,opportunitiesEvaluated:evaluation?.opportunities?.length??0,opportunitiesSaved:saved,persisted:true});
  }}catch(error){scans.push({sport,persisted:false,error:error instanceof Error?error.message:'scan failed'})}}
 return NextResponse.json({ok:scans.some(s=>s.persisted),autonomous:true,database:'neon',model:'statistical-opportunity-engine',earlyMarketTracking:true,competitionsScanned:sports.length,discoveryHorizonHours:DISCOVERY_HOURS,deepAnalysisHorizonHours:DEEP_ANALYSIS_HOURS,earlyAnalysisHorizonHours:EARLY_ANALYSIS_HOURS,maxDeepAnalysesPerRun:1,maxEarlyAnalysesPerRun:1,startedAt,finishedAt:new Date().toISOString(),scans});}
