import { NextResponse } from 'next/server';
import { getUpcomingMarketFeeds,type RadarPrice } from '../../../../lib/live-markets';
import { getPropLineSports } from '../../../../lib/propline';
import { footballRequest, type FootballFixture } from '../../../../lib/football';
import { evaluatePrices } from '../../../../lib/opportunity-engine';
import { bet365ArgentinaFixtures,bet365ArgentinaOdds,fixtureMatchScore,normalizeBet365ArgentinaOdds,oddsPapiMarkets,buildMarketCatalog } from '../../../../lib/oddspapi';
import { ensureEarlyMarketTable,ensureOpportunityHistoryColumn,ensureScanDiagnosticsTable,saveScanDiagnostics,saveOpportunity,saveScan,trackEarlyMarket } from '../../../../lib/db';
export const dynamic='force-dynamic';export const maxDuration=300;
const FALLBACK_SPORTS=['soccer_epl','soccer_argentina_primera','soccer_uefa_champions_league'];
const WANTED=/(epl|premier|argentina|bundesliga|germany|la_liga|laliga|spain|serie_a|italy|ligue_1|france|champions|europa|copa)/i;
const DISCOVERY_HOURS=168,DEEP_ANALYSIS_HOURS=24,EARLY_ANALYSIS_HOURS=168,MAX_DEEP_ANALYSES=3,MAX_EARLY_ANALYSES=5;
const fixtureCache=new Map<string,FootballFixture[]>();let localFixtures:any[]|null=null;let marketCatalog:any=null;
async function activeSports(){try{const all=await getPropLineSports();const selected=all.filter(s=>s.active&&s.key.startsWith('soccer_')&&WANTED.test(`${s.key} ${s.title}`)).map(s=>s.key);return selected.length?selected.slice(0,12):FALLBACK_SPORTS}catch{return FALLBACK_SPORTS}}
async function candidateFixtures(commenceTime?:string){if(!commenceTime)return[];const day=new Date(commenceTime).toISOString().slice(0,10);if(fixtureCache.has(day))return fixtureCache.get(day)!;const data=await footballRequest<{response:FootballFixture[]}>(`/fixtures?date=${day}&timezone=America%2FArgentina%2FBuenos_Aires`,21600);const fixtures=data.response??[];fixtureCache.set(day,fixtures);return fixtures}
function hoursUntil(value?:string|null){if(!value)return Infinity;return (Date.parse(value)-Date.now())/3600000}
function summarizeEvaluation(e:any){const xs=e?.opportunities??[];const byStatus:Record<string,number>={};let insufficientSample=0;for(const o of xs){const s=o.decision?.status??'SIN ESTADO';byStatus[s]=(byStatus[s]??0)+1;if((o.sampleSize??0)<3)insufficientSample++}return{evaluated:xs.length,byStatus,insufficientSample,publishable:xs.filter((o:any)=>o.decision?.status!=='SIN MODELO'&&o.decision?.status!=='DESCARTAR'&&o.sampleSize>=3).length}}
function marketKey(name:string){const s=name.toLowerCase();if(/shot.*target|shots on target/.test(s))return'player_shots_on_target';if(/player.*shot|shots/.test(s))return'player_shots';if(/save/.test(s))return'goalie_saves';if(/card/.test(s))return'player_cards';if(/anytime.*score|goalscorer|to score/.test(s))return'anytime_goal_scorer';if(/goal.*assist|score.*assist/.test(s))return'goal_or_assist';if(/foul/.test(s))return'player_fouls';return''}
async function localPrices(event:any):Promise<RadarPrice[]>{if(!process.env.ODDSPAPI_API_KEY||!event?.commence_time)return[];try{if(!localFixtures){const now=new Date(),to=new Date(now.getTime()+47*3600000);const raw:any=await bet365ArgentinaFixtures(now.toISOString(),to.toISOString());localFixtures=Array.isArray(raw)?raw:(raw?.fixtures??raw?.data??[])}if(!marketCatalog)marketCatalog=buildMarketCatalog(await oddsPapiMarkets());const ranked=localFixtures.map(f=>({f,s:fixtureMatchScore(f,event.home_team??'',event.away_team??'',event.commence_time)})).sort((a,b)=>b.s-a.s);if(!ranked[0]||ranked[0].s<6)return[];const raw=await bet365ArgentinaOdds({fixtureId:String(ranked[0].f.fixtureId)});return normalizeBet365ArgentinaOdds(raw,marketCatalog).map(o=>({sport:'soccer',eventId:String(event.id),home:event.home_team??o.home,away:event.away_team??o.away,commenceTime:event.commence_time??o.startTime,bookmaker:'Bet365 ARG',bookmakerKey:'bet365.bet.ar',market:marketKey(o.marketName),player:o.player??'',outcome:o.outcome,line:o.line,decimalOdds:o.decimalOdds})).filter(p=>p.market&&p.decimalOdds>1)}catch{return[]}}
export async function GET(request:Request){const secret=process.env.CRON_SECRET;if(secret&&request.headers.get('authorization')!==`Bearer ${secret}`)return NextResponse.json({ok:false,error:'Unauthorized'},{status:401});const startedAt=new Date().toISOString(),scans:any[]=[];let deepAnalyses=0,earlyAnalyses=0;await Promise.all([ensureEarlyMarketTable(),ensureOpportunityHistoryColumn(),ensureScanDiagnosticsTable()]);const sports=await activeSports();
for(const sport of sports){try{const feeds=await getUpcomingMarketFeeds(sport,4,20,DISCOVERY_HOURS);if(!feeds.length){const scanId=await saveScan({startedAt,sport,event:null,bookmakers:0,bet365Available:false,prices:0});scans.push({sport,scanId,persisted:true,reason:'No event inside discovery horizon'});continue}for(const feed of feeds){const event={id:String(feed.event.id),home_team:feed.event.home_team??null,away_team:feed.event.away_team??null,commence_time:feed.event.commence_time??null};const local=await localPrices(event);const prices=local.length?local:feed.prices;const scanId=await saveScan({startedAt,sport,event,bookmakers:feed.bookmakers.length+(local.length?1:0),bet365Available:local.length>0,prices:prices.length});let tracked=0;for(const p of prices){await trackEarlyMarket(sport,event,p);tracked++}let evaluation:any=null,saved=0;const h=hoursUntil(event.commence_time),nearKickoff=h<=DEEP_ANALYSIS_HOURS&&h>=-0.5,earlyWindow=h<=EARLY_ANALYSIS_HOURS&&h>DEEP_ANALYSIS_HOURS;const shouldAnalyze=(nearKickoff&&deepAnalyses<MAX_DEEP_ANALYSES)||(earlyWindow&&earlyAnalyses<MAX_EARLY_ANALYSES);if(shouldAnalyze&&prices.length&&process.env.FOOTBALL_API_KEY){if(nearKickoff)deepAnalyses++;else earlyAnalyses++;const fixtures=await candidateFixtures(event.commence_time??undefined);evaluation=await evaluatePrices(event,prices,fixtures);const analysisType=nearKickoff?'deep':'early';await saveScanDiagnostics(scanId,sport,event,analysisType,evaluation);const publishable=(evaluation.opportunities??[]).filter((o:any)=>o.decision?.status!=='SIN MODELO'&&o.decision?.status!=='DESCARTAR'&&o.sampleSize>=3);for(const o of publishable){await saveOpportunity(scanId,sport,event,o);saved++}}scans.push({sport,scanId,event,bet365Argentina:local.length,prices:prices.length,earlyPricesTracked:tracked,fixtureMatched:Boolean(evaluation?.matched),lineupConfirmed:Boolean(evaluation?.lineupConfirmed),analysis:nearKickoff&&evaluation?'deep':earlyWindow&&evaluation?'early':false,diagnostics:evaluation?summarizeEvaluation(evaluation):null,opportunitiesEvaluated:evaluation?.opportunities?.length??0,opportunitiesSaved:saved,persisted:true})}}catch(error){scans.push({sport,persisted:false,error:error instanceof Error?error.message:'scan failed'})}}
const analyzed=scans.filter(s=>s.analysis);const diagnostics=analyzed.reduce((acc:any,s:any)=>{acc.matches++;acc.markets+=s.diagnostics?.evaluated??0;acc.insufficientSample+=s.diagnostics?.insufficientSample??0;for(const[k,v]of Object.entries(s.diagnostics?.byStatus??{}))acc.byStatus[k]=(acc.byStatus[k]??0)+(v as number);acc.saved+=s.opportunitiesSaved??0;return acc},{matches:0,markets:0,insufficientSample:0,byStatus:{},saved:0});return NextResponse.json({ok:scans.some(s=>s.persisted),autonomous:true,localBookmaker:'bet365.bet.ar',competitionsScanned:sports.length,diagnostics,startedAt,finishedAt:new Date().toISOString(),scans})}
