import { earlyMarketSignals,recentOpportunities,radarSummary,radarLaboratory } from '../lib/db';
function localDate(value:string){return new Intl.DateTimeFormat('es-AR',{timeZone:'America/Argentina/Buenos_Aires',weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}function marketName(key:string){const n:Record<string,string>={player_shots:'REMATES',player_shots_on_target:'AL ARCO',goalie_saves:'ATAJADAS',player_cards:'TARJETAS',anytime_goal_scorer:'GOL',goal_or_assist:'GOL O ASISTENCIA'};return n[key]??key.toUpperCase()}function pct(v:any){const n=Number(v);return Number.isFinite(n)?`${(n*100).toFixed(0)}%`:'—'}function num(v:any){const n=Number(v);return Number.isFinite(n)?n.toFixed(2):'—'}function form(v:any){if(Array.isArray(v))return v;if(typeof v==='string'){try{return JSON.parse(v)}catch{return[]}}return[]}
export const dynamic='force-dynamic';
export default async function Home(){let rows:any[]=[],early:any[]=[],summary:any=null,lab:any=null,databaseOk=true;try{[rows,summary,lab]=await Promise.all([recentOpportunities(80).then(x=>Array.from(x) as any[]),radarSummary(),radarLaboratory()])}catch{databaseOk=false}if(databaseOk){try{early=Array.from(await earlyMarketSignals(30)) as any[]}catch{early=[]}}const now=Date.now();const visible=rows.filter(r=>r.result==='PENDING'&&r.status!=='DESCARTAR'&&(!r.commence_time||Date.parse(r.commence_time)>now-3*3600000)).slice(0,12);const earlyVisible=early.slice(0,10);const wins=Number(summary?.wins??0),losses=Number(summary?.losses??0),graded=wins+losses;
return <main className="appShell"><header className="topbar"><div className="brand"><div className="radarLogo">◎</div><div><strong>Radar<span>365</span></strong><small>DATOS · ANÁLISIS · OPORTUNIDADES</small></div></div><div className={`status ${databaseOk?'on':'off'}`}><i/>{databaseOk?'En vivo':'Sin conexión'}</div></header>
<nav className="tabs"><a className="active" href="#resumen">Resumen</a><a href="#oportunidades">Oportunidades</a><a href="#anticipadas">Anticipadas</a><a href="#historial">Historial</a></nav>
<section id="resumen" className="stats"><div><span>▤</span><b>{lab?.prices24??0}</b><small>Precios leídos</small></div><div><span>↗</span><b>{lab?.tracked24??0}</b><small>Cuotas seguidas</small></div><div><span>◉</span><b>{lab?.modelled24??0}</b><small>Modeladas</small></div><div><span>☆</span><b>{lab?.candidates24??0}</b><small>Candidatas</small></div></section>
<section id="oportunidades" className="signalHero"><div className="target">◎</div><div><small>PRÓXIMOS PARTIDOS</small><h1>{visible.length?`${visible.length} oportunidades detectadas`:'Sin oportunidades detectadas'}</h1><p>{visible.length?'Señales que superaron el filtro estadístico actual.':'Radar sigue leyendo y modelando mercados. No se publica una señal hasta superar el filtro.'}</p></div></section>
{visible.length>0&&<section className="list"><div className="sectionTitle"><div><h2>Oportunidades</h2><p>Señales del modelo</p></div></div>{visible.map((o:any)=>{const recent=form(o.recent_form),hits=recent.filter((x:any)=>x.hit).length;return <article className="rowCard" key={o.id}><div className="ball">◉</div><div className="rowMain"><span className="pill">{marketName(o.market)}</span><h3>{o.player||o.outcome}</h3><p>{o.home_team} vs {o.away_team}</p><small>{o.commence_time?localDate(o.commence_time):''}{recent.length?` · últimos ${recent.length}: ${hits}/${recent.length}`:''}</small></div><div className="rowSide"><b>{num(o.decimal_odds)}</b><small>{o.status}</small><span>›</span></div></article>})}</section>}
<section id="anticipadas" className="list"><div className="sectionTitle"><div><h2>⌁ Cuotas en seguimiento</h2><p>Anticipadas · Próximos 7 días</p></div><span className="count">{earlyVisible.length}</span></div>{earlyVisible.length?earlyVisible.map((o:any)=><article className="rowCard" key={`early-${o.id}`}><div className="ball">◉</div><div className="rowMain"><span className="pill">{marketName(o.market)}</span><h3>{o.player||o.outcome}</h3><p>{o.home_team} vs {o.away_team}</p><small>{o.commence_time?localDate(o.commence_time):''} · {o.bookmaker} · {o.observations} lecturas</small></div><div className="rowSide"><b>{num(o.current_odds)}</b><small className={Number(o.movement)>0?'positive':''}>{Number(o.movement)?`${pct(o.movement)} mov.`:'Sin cambio'}</small><span>›</span></div></article>):<div className="emptyState">Todavía no hay cuotas anticipadas activas.</div>}</section>
<section id="historial" className="miniInfo"><div><small>Último análisis</small><b>{summary?.last_scan?localDate(summary.last_scan):'—'}</b></div><div><small>Resultados guardados</small><b>{graded}</b></div></section>
<footer>Radar 365 analiza datos y cuotas. Ninguna señal garantiza un resultado.</footer>
<nav className="bottomNav"><a className="active" href="#resumen"><b>⌂</b><small>Inicio</small></a><a href="#oportunidades"><b>◎</b><small>Oportunidades</small></a><a href="#anticipadas"><b>↗</b><small>Anticipadas</small></a><a href="#historial"><b>▤</b><small>Historial</small></a></nav></main>}
