import { earlyMarketSignals,recentOpportunities,radarSummary,radarLaboratory } from '../lib/db';
function localDate(value:string){return new Intl.DateTimeFormat('es-AR',{timeZone:'America/Argentina/Buenos_Aires',weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}
function marketName(key:string){const n:Record<string,string>={player_shots:'REMATES',player_shots_on_target:'AL ARCO',goalie_saves:'ATAJADAS',player_cards:'TARJETAS',player_fouls:'FALTAS',anytime_goal_scorer:'GOL',goal_or_assist:'GOL O ASISTENCIA'};return n[key]??key.toUpperCase()}
function num(v:any){const n=Number(v);return Number.isFinite(n)?n.toFixed(2):'—'}function pct(v:any){const n=Number(v);return Number.isFinite(n)?`${(n*100).toFixed(1)}%`:'—'}function form(v:any){if(Array.isArray(v))return v;if(typeof v==='string'){try{return JSON.parse(v)}catch{return[]}}return[]}
function betLabel(o:any){const outcome=String(o?.outcome??'').trim();const line=o?.line===null||o?.line===undefined||o?.line===''?null:Number(o.line);const over=/^over$/i.test(outcome),under=/^under$/i.test(outcome);if((over||under)&&Number.isFinite(line))return `${over?'Más de':'Menos de'} ${line}`;if((over||under)&&!Number.isFinite(line))return `${outcome} · Línea no identificada`;return outcome||'Mercado'}
const LOCAL_BOOKS=[/bet\s*365/i,/betwarrior/i,/betano/i,/betsson/i,/bplay/i,/sportium/i,/codere/i];function isLocalBook(v:any){return LOCAL_BOOKS.some(r=>r.test(String(v??'')))}
export const dynamic='force-dynamic';
export default async function Home(){let rows:any[]=[],early:any[]=[],summary:any=null,lab:any=null,databaseOk=true;try{[rows,summary,lab]=await Promise.all([recentOpportunities(120).then(x=>Array.from(x) as any[]),radarSummary(),radarLaboratory()])}catch{databaseOk=false}if(databaseOk){try{early=Array.from(await earlyMarketSignals(50)) as any[]}catch{early=[]}}const now=Date.now();const visible=rows.filter(r=>r.result==='PENDING'&&r.status!=='DESCARTAR'&&isLocalBook(r.bookmaker)&&(!r.commence_time||Date.parse(r.commence_time)>now-3*3600000)).sort((a,b)=>Number(b.edge??0)-Number(a.edge??0)).slice(0,12);const earlyLocal=early.filter(o=>isLocalBook(o.bookmaker));const displayEarly=(earlyLocal.length?earlyLocal:early).slice(0,12);const wins=Number(summary?.wins??0),losses=Number(summary?.losses??0),graded=wins+losses;
return <main className="appShell"><header className="topbar"><div className="brand"><div className="radarLogo">◎</div><div><strong>Radar<span>365</span></strong><small>DATOS · ANÁLISIS · OPORTUNIDADES</small></div></div><div className={`status ${databaseOk?'on':'off'}`}><i/>{databaseOk?'RADAR EN VIVO':'Sin conexión'}</div></header>
<nav className="tabs"><a className="active" href="#oportunidades">Radar</a><a href="#anticipadas">Anticipadas</a><a href="#historial">Resultados</a></nav>
<section id="oportunidades" className="signalHero"><div className="target">◎</div><div><small>MEJORES OPORTUNIDADES AHORA</small><h1>{visible.length?`${visible.length} señales con valor detectado`:'Sin valor local confirmado ahora'}</h1><p>{visible.length?'Ordenadas por ventaja estimada, sin forzar mercados.':'Radar sigue escaneando cuotas y datos. Solo publica cuando puede justificar una señal con cuota disponible en Argentina.'}</p></div></section>
<section className="stats"><div><span>◎</span><b>{lab?.prices24??0}</b><small>Precios 24 h</small></div><div><span>↗</span><b>{lab?.tracked24??0}</b><small>Cuotas seguidas</small></div><div><span>◉</span><b>{lab?.modelled24??0}</b><small>Analizadas</small></div><div><span>☆</span><b>{lab?.candidates24??0}</b><small>Con valor</small></div></section>
{visible.length>0&&<section className="list"><div className="sectionTitle"><div><h2>Radar de valor</h2><p>Probabilidad propia vs cuota del mercado</p></div></div>{visible.map((o:any)=>{const recent=form(o.recent_form),hits=recent.filter((x:any)=>x.hit).length;return <article className="rowCard" key={o.id}><div className="ball">◎</div><div className="rowMain"><span className="pill">{marketName(o.market)} · {o.status}</span><h3>{o.player||o.outcome}</h3><p>{betLabel(o)} · {o.home_team} vs {o.away_team}</p><small>{o.commence_time?localDate(o.commence_time):''}{recent.length?` · Últimos ${recent.length}: ${hits}/${recent.length}`:''}</small><small>Radar {pct(o.model_probability)} · Justa {num(o.fair_odds)} · EV {pct(o.edge)}</small></div><div className="rowSide"><b>{num(o.decimal_odds)}</b><small>{o.bookmaker}</small><span>›</span></div></article>})}</section>}
<section id="anticipadas" className="list"><div className="sectionTitle"><div><h2>⚡ Anticipadas</h2><p>Cuotas detectadas antes del partido</p></div><span className="count">{displayEarly.length}</span></div>{displayEarly.length?displayEarly.map((o:any)=>{const local=isLocalBook(o.bookmaker);const open=Number(o.opening_odds),current=Number(o.current_odds),move=open>0?(current-open)/open:null;return <article className="rowCard" key={`early-${o.id}`}><div className="ball">↗</div><div className="rowMain"><span className="pill">{marketName(o.market)}</span><h3>{o.player||o.outcome}</h3><p>{o.player?`${betLabel(o)} · `:''}{o.home_team} vs {o.away_team}</p><small>{o.commence_time?localDate(o.commence_time):''} · {local?o.bookmaker:'Referencia internacional'}</small><small>Inicial {num(o.opening_odds)} · Actual {num(o.current_odds)}{move!==null?` · Movimiento ${(move*100).toFixed(1)}%`:''}</small></div><div className="rowSide">{local?<><b>{num(o.current_odds)}</b><small>Cuota local</small></>:<><b>—</b><small>Sin cuota local</small></>}<span>›</span></div></article>}):<div className="emptyState">No hay mercados futuros capturados todavía.</div>}</section>
<section id="historial" className="miniInfo"><div><small>Último escaneo</small><b>{summary?.last_scan?localDate(summary.last_scan):'—'}</b></div><div><small>Forward test liquidado</small><b>{graded} · {wins} W / {losses} L</b></div></section>
<footer>Radar 365 estima probabilidades y valor esperado. No garantiza resultados.</footer><nav className="bottomNav"><a className="active" href="#oportunidades"><b>◎</b><small>Radar</small></a><a href="#anticipadas"><b>↗</b><small>Anticipadas</small></a><a href="#historial"><b>▤</b><small>Resultados</small></a><a href="#oportunidades"><b>⌁</b><small>Más</small></a></nav></main>}
