import { neon } from '@neondatabase/serverless';
function db(){const url=process.env.DATABASE_URL;if(!url)throw new Error('DATABASE_URL is not configured');return neon(url)}
export async function saveScan(input:{startedAt:string;sport:string;event:any;bookmakers:number;bet365Available:boolean;prices:number}){const sql=db();const rows=await sql`INSERT INTO radar_scans(started_at,sport,event_id,home_team,away_team,commence_time,bookmakers_count,bet365_available,prices_count) VALUES(${input.startedAt},${input.sport},${input.event?.id?String(input.event.id):null},${input.event?.home_team??null},${input.event?.away_team??null},${input.event?.commence_time??null},${input.bookmakers},${input.bet365Available},${input.prices}) RETURNING id`;return Number(rows[0].id)}
export async function ensureOpportunityHistoryColumn(){const sql=db();await sql`ALTER TABLE radar_opportunities ADD COLUMN IF NOT EXISTS recent_form JSONB`}
export async function saveOpportunity(scanId:number,sport:string,event:any,o:any){const sql=db();await sql`INSERT INTO radar_opportunities(scan_id,fixture_id,sport,event_id,home_team,away_team,commence_time,player,market,outcome,line,bookmaker,decimal_odds,model_probability,fair_odds,edge,status,sample_size,lineup_confirmed,confirmed_starter,unavailable,recent_form) VALUES(${scanId},${o.fixtureId??null},${sport},${String(event.id)},${event.home_team??''},${event.away_team??''},${event.commence_time??null},${o.player??null},${o.market},${o.outcome??null},${o.line??null},${o.bookmaker??null},${o.decimalOdds},${o.estimate?.probability??null},${o.decision?.fairOdds??null},${o.decision?.edge??null},${o.decision?.status??'DESCARTAR'},${o.sampleSize??0},${Boolean(o.lineupConfirmed)},${Boolean(o.confirmedStarter)},${Boolean(o.unavailable)},${JSON.stringify(o.recentForm??[])}) ON CONFLICT DO NOTHING`}
export async function ensureEarlyMarketTable(){const sql=db();await sql`CREATE TABLE IF NOT EXISTS radar_early_markets(id BIGSERIAL PRIMARY KEY,sport TEXT NOT NULL,event_id TEXT NOT NULL,home_team TEXT,away_team TEXT,commence_time TIMESTAMPTZ,player TEXT,market TEXT NOT NULL,outcome TEXT,bookmaker TEXT NOT NULL,opening_odds NUMERIC NOT NULL,current_odds NUMERIC NOT NULL,best_odds NUMERIC NOT NULL,lowest_odds NUMERIC NOT NULL,first_seen TIMESTAMPTZ NOT NULL DEFAULT now(),last_seen TIMESTAMPTZ NOT NULL DEFAULT now(),observations INTEGER NOT NULL DEFAULT 1,UNIQUE(event_id,market,player,outcome,bookmaker))`}
export async function trackEarlyMarket(sport:string,event:any,p:any){const sql=db();await sql`INSERT INTO radar_early_markets(sport,event_id,home_team,away_team,commence_time,player,market,outcome,bookmaker,opening_odds,current_odds,best_odds,lowest_odds) VALUES(${sport},${String(event.id)},${event.home_team??null},${event.away_team??null},${event.commence_time??null},${p.player??null},${p.market},${p.outcome??null},${p.bookmaker},${p.decimalOdds},${p.decimalOdds},${p.decimalOdds},${p.decimalOdds}) ON CONFLICT(event_id,market,player,outcome,bookmaker) DO UPDATE SET current_odds=EXCLUDED.current_odds,best_odds=GREATEST(radar_early_markets.best_odds,EXCLUDED.current_odds),lowest_odds=LEAST(radar_early_markets.lowest_odds,EXCLUDED.current_odds),last_seen=now(),observations=radar_early_markets.observations+1`}
export async function earlyMarketSignals(limit=30){const sql=db();return sql`SELECT *,CASE WHEN opening_odds>0 THEN (opening_odds-current_odds)/opening_odds ELSE 0 END AS movement FROM radar_early_markets WHERE commence_time>now() ORDER BY first_seen DESC LIMIT ${limit}`}
export async function recentOpportunities(limit=50){const sql=db();return sql`SELECT * FROM radar_opportunities ORDER BY captured_at DESC LIMIT ${limit}`}
export async function pendingOpportunities(limit=100){const sql=db();return sql`SELECT * FROM radar_opportunities WHERE result='PENDING' AND fixture_id IS NOT NULL AND commence_time < now()-interval '2 hours' ORDER BY commence_time ASC LIMIT ${limit}`}
export async function settleOpportunity(id:number,result:'WIN'|'LOSS'|'VOID',value:number|null){const sql=db();await sql`UPDATE radar_opportunities SET result=${result},settled_value=${value},settled_at=now() WHERE id=${id} AND result='PENDING'`}
export async function radarSummary(){const sql=db();const rows=await sql`SELECT (SELECT count(*)::int FROM radar_scans) AS scans,(SELECT count(*)::int FROM radar_opportunities) AS opportunities,(SELECT max(finished_at) FROM radar_scans) AS last_scan,(SELECT max(captured_at) FROM radar_opportunities) AS last_opportunity,(SELECT count(*)::int FROM radar_opportunities WHERE status='VERDE') AS green,(SELECT count(*)::int FROM radar_opportunities WHERE status='AMARILLO') AS yellow,(SELECT count(*)::int FROM radar_opportunities WHERE result='PENDING') AS pending,(SELECT count(*)::int FROM radar_opportunities WHERE result='WIN') AS wins,(SELECT count(*)::int FROM radar_opportunities WHERE result='LOSS') AS losses`;return rows[0]??{scans:0,opportunities:0,last_scan:null,last_opportunity:null,green:0,yellow:0,pending:0,wins:0,losses:0}}
export async function radarLaboratory(){const sql=db();const rows=await sql`SELECT (SELECT count(*)::int FROM radar_scans WHERE started_at>now()-interval '24 hours') AS scans24,(SELECT coalesce(sum(prices_count),0)::int FROM radar_scans WHERE started_at>now()-interval '24 hours') AS prices24,(SELECT count(DISTINCT event_id)::int FROM radar_scans WHERE started_at>now()-interval '24 hours' AND event_id IS NOT NULL) AS events24,(SELECT count(DISTINCT sport)::int FROM radar_scans WHERE started_at>now()-interval '24 hours') AS sports24,(SELECT count(*)::int FROM radar_early_markets WHERE last_seen>now()-interval '24 hours') AS tracked24,(SELECT count(*)::int FROM radar_opportunities WHERE captured_at>now()-interval '24 hours') AS modelled24,(SELECT count(*)::int FROM radar_opportunities WHERE captured_at>now()-interval '24 hours' AND status='DESCARTAR') AS discarded24,(SELECT count(*)::int FROM radar_opportunities WHERE captured_at>now()-interval '24 hours' AND status IN ('AMARILLO','VERDE')) AS candidates24`;return rows[0]??{scans24:0,prices24:0,events24:0,sports24:0,tracked24:0,modelled24:0,discarded24:0,candidates24:0}}
