const BASE_URL=process.env.FOOTBALL_API_BASE_URL||'https://v3.football.api-sports.io';
export type FootballFixture={fixture:{id:number;date:string;status:{short:string;long:string}};league:{id:number;name:string;country:string;logo?:string};teams:{home:{id:number;name:string;logo?:string};away:{id:number;name:string;logo?:string}}};
export async function footballRequest<T>(path:string,revalidate=1800):Promise<T>{const key=process.env.FOOTBALL_API_KEY;if(!key)throw new Error('FOOTBALL_API_KEY is not configured');const response=await fetch(`${BASE_URL}${path}`,{headers:{'x-apisports-key':key},next:{revalidate}});if(!response.ok)throw new Error(`API-Football error ${response.status}`);return response.json() as Promise<T>}
export async function getFixturesByDate(date:string,timezone='America/Argentina/Buenos_Aires'){return footballRequest<{response:FootballFixture[];errors:unknown}>(`/fixtures?date=${encodeURIComponent(date)}&timezone=${encodeURIComponent(timezone)}`,1800)}
export async function getRecentTeamFixtures(teamId:number,last=10){return footballRequest<{response:FootballFixture[];errors:unknown}>(`/fixtures?team=${teamId}&last=${Math.min(last,10)}&status=FT`,21600)}
export type FixturePlayer={player:{id:number;name:string};statistics:Array<{games?:{minutes?:number|null;position?:string};shots?:{total?:number|null;on?:number|null};goals?:{total?:number|null;assists?:number|null;saves?:number|null};cards?:{yellow?:number|null;red?:number|null}}>};
export type FixturePlayersTeam={team:{id:number;name:string};players:FixturePlayer[]};
export async function getFixturePlayers(fixtureId:number){return footballRequest<{response:FixturePlayersTeam[];errors:unknown}>(`/fixtures/players?fixture=${fixtureId}`,86400)}
const norm=(s:string)=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
export type PlayerSampleMarket='player_shots'|'player_shots_on_target'|'goalie_saves'|'player_cards'|'anytime_goal_scorer'|'goal_or_assist';
export async function getHistoricalPlayerSamples(teamId:number,playerName:string,market:PlayerSampleMarket,last=8){const fixtures=await getRecentTeamFixtures(teamId,last);const batches=await Promise.all((fixtures.response??[]).map(f=>getFixturePlayers(f.fixture.id)));const target=norm(playerName);const samples:Array<{value:number;minutes?:number}>=[];for(const batch of batches){for(const team of batch.response??[]){const found=team.players?.find(p=>{const n=norm(p.player.name);return n.includes(target)||target.includes(n)});const s=found?.statistics?.[0];if(!s)continue;let value:number|null|undefined;if(market==='player_shots')value=s.shots?.total;else if(market==='player_shots_on_target')value=s.shots?.on;else if(market==='goalie_saves')value=s.goals?.saves;else if(market==='player_cards')value=(s.cards?.yellow??0)+(s.cards?.red??0);else if(market==='anytime_goal_scorer')value=(s.goals?.total??0)>0?1:0;else value=((s.goals?.total??0)+(s.goals?.assists??0))>0?1:0;if(typeof value==='number')samples.push({value,minutes:s.games?.minutes??undefined})}}return samples}

type TeamStats={team?:{id?:number};statistics?:Array<{type?:string;value?:number|string|null}>};
function statValue(stats:TeamStats[],teamId:number,label:string){const row=stats.find(x=>x.team?.id===teamId)?.statistics?.find(x=>x.type===label)?.value;if(typeof row==='number')return row;if(typeof row==='string'){const n=Number(row.replace('%',''));return Number.isFinite(n)?n:null}return null}
export async function getHistoricalTeamSamples(teamId:number,market:'corners'|'goals',last=6){const fixtures=await getRecentTeamFixtures(teamId,last);const out:number[]=[];for(const f of fixtures.response??[]){if(market==='goals'){const raw=await footballRequest<any>(`/fixtures?id=${f.fixture.id}`,86400);const item=raw.response?.[0];const isHome=item?.teams?.home?.id===teamId;const v=isHome?item?.goals?.home:item?.goals?.away;if(typeof v==='number')out.push(v)}else{const raw=await footballRequest<{response:TeamStats[]}>(`/fixtures/statistics?fixture=${f.fixture.id}`,86400);const v=statValue(raw.response??[],teamId,'Corner Kicks');if(typeof v==='number')out.push(v)}}return out.map(value=>({value,minutes:90}))}
