const BASE='https://api.oddspapi.io/v4';
function apiKey(){const k=process.env.ODDSPAPI_API_KEY;if(!k)throw new Error('OddsPapi not configured');return k}
export async function oddsPapiRequest(path:string,params:Record<string,string>={}){const q=new URLSearchParams(params);q.set('apiKey',apiKey());const r=await fetch(`${BASE}${path}?${q}`,{cache:'no-store'});if(!r.ok){const body=await r.text().catch(()=> '');throw new Error(`OddsPapi ${r.status}${body?`: ${body.slice(0,180)}`:''}`)}return r.json()}
export async function oddsPapiAccount(){return oddsPapiRequest('/account')}
export async function bet365ArgentinaOdds(params:Record<string,string>={}){return oddsPapiRequest('/odds',{...params,bookmakers:'bet365.bet.ar',oddsFormat:'decimal',language:'en',verbosity:'3'})}
export async function bet365ArgentinaFixtures(from:string,to:string){return oddsPapiRequest('/fixtures',{sportId:'10',from,to,statusId:'0',hasOdds:'true',bookmakers:'bet365.bet.ar',language:'en'})}
export function normalizeName(v:any){return String(v??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(fc|cf|afc|club|deportivo|calcio)\b/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
export function fixtureTeams(f:any){return{home:String(f?.participant1Name??f?.participants?.participant1Name??f?.participants?.home?.name??''),away:String(f?.participant2Name??f?.participants?.participant2Name??f?.participants?.away?.name??'')}}
export function fixtureMatchScore(f:any,home:string,away:string,time?:string){const h=normalizeName(home),a=normalizeName(away),teams=fixtureTeams(f),fh=normalizeName(teams.home),fa=normalizeName(teams.away);let s=0;if(h&&fh===h)s+=4;else if(h&&fh&&(fh.includes(h)||h.includes(fh)))s+=2;if(a&&fa===a)s+=4;else if(a&&fa&&(fa.includes(a)||a.includes(fa)))s+=2;if(time&&f?.startTime&&Math.abs(Date.parse(time)-Date.parse(f.startTime))<3*3600000)s+=2;return s}
function decimal(v:any){const n=Number(v);return Number.isFinite(n)&&n>1?n:null}
export type LocalOdd={fixtureId:string;home:string;away:string;startTime:string;market:string;marketName:string;player:string|null;outcome:string;line:number|null;decimalOdds:number;bookmaker:string};
export function normalizeBet365ArgentinaOdds(raw:any):LocalOdd[]{const out:LocalOdd[]=[];const fixtureId=String(raw?.fixtureId??'');const teams=fixtureTeams(raw);const home=teams.home,away=teams.away;const startTime=String(raw?.startTime??'');const root=raw?.bookmakerOdds?.['bet365.bet.ar']??raw?.bookmakers?.['bet365.bet.ar']??raw?.bookmakers?.find?.((b:any)=>b?.slug==='bet365.bet.ar'||b?.bookmakerSlug==='bet365.bet.ar')??raw?.odds?.['bet365.bet.ar']??raw?.odds??raw;const seen=new Set<any>();function walk(x:any,ctx:any={}){if(!x||typeof x!=='object'||seen.has(x))return;seen.add(x);const marketName=String(x.marketName??x.market?.name??ctx.marketName??'');const player=String(x.playerName??x.player?.name??ctx.player??'')||null;const outcome=String(x.outcomeName??x.name??x.label??ctx.outcome??'');const price=decimal(x.decimalOdds??x.oddsDecimal??x.price??x.odds);const lineRaw=x.line??x.handicap??x.points??x.total;const line=Number.isFinite(Number(lineRaw))?Number(lineRaw):null;if(price&&marketName&&outcome)out.push({fixtureId,home,away,startTime,market:normalizeName(marketName).replace(/ /g,'_'),marketName,player,outcome,line,decimalOdds:price,bookmaker:'Bet365 ARG'});const next={marketName:String(x.marketName??x.market?.name??ctx.marketName??''),player:String(x.playerName??x.player?.name??ctx.player??'')||null,outcome:String(x.outcomeName??ctx.outcome??'')};for(const v of Object.values(x))if(v&&typeof v==='object')walk(v,next)}walk(root);const unique=new Map<string,LocalOdd>();for(const o of out)unique.set(`${o.marketName}|${o.player}|${o.outcome}|${o.line}|${o.decimalOdds}`,o);return [...unique.values()]}
