import { getHistoricalPlayerSamplesBatch,samplesFromBatch,getHistoricalTeamSamples,footballRequest,type FootballFixture,type PlayerSampleMarket,type HistoricalPlayerRequest } from './football';
import { estimateOverProbability,valueDecision,requiredCount } from './stat-model';
import { matchFixture } from './matcher';import type{RadarPrice}from'./live-markets';
type Lineup={team?:{id?:number};startXI?:Array<{player?:{name?:string}}>};type Injury={player?:{name?:string}};const norm=(s:string)=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function playerInLineup(ls:Lineup[],name:string){const t=norm(name);return ls.some(l=>(l.startXI??[]).some(x=>{const n=norm(x.player?.name??'');return n&&(n.includes(t)||t.includes(n))}))}function injured(xs:Injury[],name:string){const t=norm(name);return xs.some(i=>{const n=norm(i.player?.name??'');return n&&(n.includes(t)||t.includes(n))})}function teamFromText(p:RadarPrice,f:FootballFixture){const t=norm(`${p.player} ${p.outcome}`),h=norm(f.teams.home.name),a=norm(f.teams.away.name);return t.includes(h)?f.teams.home.id:t.includes(a)?f.teams.away.id:null}
const playerMarkets=new Set<PlayerSampleMarket>(['player_shots','player_shots_on_target','goalie_saves','player_cards','anytime_goal_scorer','goal_or_assist']);
function binaryProbability(samples:Array<{value:number}>,line:number){if(samples.length<4)return null;const needed=Math.max(1,requiredCount(line)),hits=samples.filter(s=>s.value>=needed).length;return(hits+1)/(samples.length+2)}
function expectedMinutes(samples:Array<{minutes?:number}>,starter:boolean){const mins=samples.map(s=>s.minutes).filter((v):v is number=>typeof v==='number'&&v>0);if(!mins.length)return starter?82:65;const avg=mins.reduce((a,b)=>a+b,0)/mins.length;return Math.max(45,Math.min(starter?95:82,avg));}
export async function evaluatePrices(event:{home_team?:string;away_team?:string;commence_time?:string},prices:RadarPrice[],candidateFixtures:FootballFixture[]){const matched=matchFixture(event,candidateFixtures);if(!matched)return{matched:false,fixture:null,opportunities:[]};const fixture=matched.fixture;
 const[ld,id]=await Promise.all([footballRequest<{response:Lineup[]}>(`/fixtures/lineups?fixture=${fixture.fixture.id}`,600),footballRequest<{response:Injury[]}>(`/injuries?fixture=${fixture.fixture.id}`,14400)]);const lineups=ld.response??[],injuries=id.response??[],lineupConfirmed=lineups.length>=2;
 const supported=prices.filter(p=>playerMarkets.has(p.market as PlayerSampleMarket)||['team_corners','total_corners','totals'].includes(p.market)).slice(0,10),opportunities:any[]=[];const playerPrices=supported.filter(p=>playerMarkets.has(p.market as PlayerSampleMarket));const requests:HistoricalPlayerRequest[]=playerPrices.map(p=>({playerName:p.player,market:p.market as PlayerSampleMarket}));
 const[homeBatch,awayBatch]=requests.length?await Promise.all([getHistoricalPlayerSamplesBatch(fixture.teams.home.id,requests,6),getHistoricalPlayerSamplesBatch(fixture.teams.away.id,requests,6)]):[{},{}];
 for(const price of supported){let samples:Array<{value:number;minutes?:number}>=[],teamId:number|null=null,confirmedStarter=false,unavailable=false;if(playerMarkets.has(price.market as PlayerSampleMarket)){const market=price.market as PlayerSampleMarket,isH=playerInLineup(lineups.filter(l=>l.team?.id===fixture.teams.home.id),price.player),isA=playerInLineup(lineups.filter(l=>l.team?.id===fixture.teams.away.id),price.player),h=samplesFromBatch(homeBatch,price.player,market),a=samplesFromBatch(awayBatch,price.player,market);teamId=isH?fixture.teams.home.id:isA?fixture.teams.away.id:h.length>=3?fixture.teams.home.id:a.length>=3?fixture.teams.away.id:null;samples=teamId===fixture.teams.home.id?h:teamId===fixture.teams.away.id?a:[];confirmedStarter=lineupConfirmed&&playerInLineup(lineups,price.player);unavailable=injured(injuries,price.player)}else{teamId=teamFromText(price,fixture);if(price.market==='team_corners'&&teamId)samples=await getHistoricalTeamSamples(teamId,'corners',4);else if(price.market==='totals'&&teamId)samples=await getHistoricalTeamSamples(teamId,'goals',6)}
  const line=price.line??(price.market==='anytime_goal_scorer'||price.market==='goal_or_assist'?0.5:null);if(line===null)continue;let estimate:any;if(price.market==='anytime_goal_scorer'||price.market==='goal_or_assist'||price.market==='player_cards'){const probability=binaryProbability(samples,line);estimate={probability,sampleSize:samples.length,confidence:samples.length>=6?'MEDIA':'BAJA'}}else estimate=estimateOverProbability({samples,line,expectedMinutes:expectedMinutes(samples,confirmedStarter),lineupConfirmed:confirmedStarter});let decision=valueDecision(estimate.probability??null,price.decimalOdds,playerMarkets.has(price.market as PlayerSampleMarket)?confirmedStarter:true);
  if(unavailable||(lineupConfirmed&&playerMarkets.has(price.market as PlayerSampleMarket)&&!confirmedStarter))decision={...decision,status:'DESCARTAR'};else if(estimate.confidence==='BAJA'&&decision.status==='VERDE')decision={...decision,status:'AMARILLO'};opportunities.push({...price,fixtureId:fixture.fixture.id,teamId,lineupConfirmed,confirmedStarter,unavailable,expectedMinutes:expectedMinutes(samples,confirmedStarter),sampleSize:samples.length,estimate,decision})}
 opportunities.sort((a,b)=>(b.decision.edge??-99)-(a.decision.edge??-99));return{matched:true,matchScore:matched.score,fixture:{id:fixture.fixture.id,home:fixture.teams.home.name,away:fixture.teams.away.name},lineupConfirmed,injuriesCount:injuries.length,opportunities};}
