import { getHistoricalPlayerSamplesBatch,samplesFromBatch,footballRequest,type FootballFixture,type PlayerSampleMarket,type HistoricalPlayerRequest } from './football';
import { estimateOverProbability,valueDecision,requiredCount } from './stat-model';
import { matchFixture } from './matcher';import type{RadarPrice}from'./live-markets';
type Lineup={team?:{id?:number};startXI?:Array<{player?:{name?:string}}>};type Injury={player?:{name?:string}};const norm=(s:string)=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
function samePlayer(a:string,b:string){const x=norm(a),y=norm(b);if(!x||!y)return false;if(x===y)return true;const xa=x.split(' '),ya=y.split(' ');const xs=xa.at(-1),ys=ya.at(-1);return Boolean(xs&&ys&&xs.length>=4&&xs===ys)}
function playerInLineup(ls:Lineup[],name:string){return ls.some(l=>(l.startXI??[]).some(x=>samePlayer(x.player?.name??'',name)))}function injured(xs:Injury[],name:string){return xs.some(i=>samePlayer(i.player?.name??'',name))}
const playerMarkets=new Set<PlayerSampleMarket>(['player_shots','player_shots_on_target','goalie_saves','player_cards','anytime_goal_scorer','goal_or_assist']);
function hasClearSemantics(p:RadarPrice){if(p.market==='anytime_goal_scorer'||p.market==='goal_or_assist')return true;return typeof p.line==='number'&&/\d+(?:\.\d+)?\s*\+/.test(p.outcome)}
function binaryProbability(samples:Array<{value:number}>,line:number){if(samples.length<4)return null;const needed=Math.max(1,requiredCount(line)),hits=samples.filter(s=>s.value>=needed).length;return(hits+1)/(samples.length+2)}
function expectedMinutes(samples:Array<{minutes?:number}>,starter:boolean){const mins=samples.map(s=>s.minutes).filter((v):v is number=>typeof v==='number'&&v>0);if(!mins.length)return starter?82:65;const avg=mins.reduce((a,b)=>a+b,0)/mins.length;return Math.max(45,Math.min(starter?95:82,avg));}
export async function evaluatePrices(event:{home_team?:string;away_team?:string;commence_time?:string},prices:RadarPrice[],candidateFixtures:FootballFixture[]){const matched=matchFixture(event,candidateFixtures);if(!matched)return{matched:false,fixture:null,opportunities:[]};const fixture=matched.fixture;const[ld,id]=await Promise.all([footballRequest<{response:Lineup[]}>(`/fixtures/lineups?fixture=${fixture.fixture.id}`,600),footballRequest<{response:Injury[]}>(`/injuries?fixture=${fixture.fixture.id}`,14400)]);const lineups=ld.response??[],injuries=id.response??[],lineupConfirmed=lineups.length>=2;
 const supported=prices.filter(p=>playerMarkets.has(p.market as PlayerSampleMarket)&&hasClearSemantics(p)).slice(0,8),opportunities:any[]=[];const requests:HistoricalPlayerRequest[]=supported.map(p=>({playerName:p.player,market:p.market as PlayerSampleMarket}));const[homeBatch,awayBatch]=requests.length?await Promise.all([getHistoricalPlayerSamplesBatch(fixture.teams.home.id,requests,6),getHistoricalPlayerSamplesBatch(fixture.teams.away.id,requests,6)]):[{},{}];
 for(const price of supported){const market=price.market as PlayerSampleMarket,isH=playerInLineup(lineups.filter(l=>l.team?.id===fixture.teams.home.id),price.player),isA=playerInLineup(lineups.filter(l=>l.team?.id===fixture.teams.away.id),price.player),h=samplesFromBatch(homeBatch,price.player,market),a=samplesFromBatch(awayBatch,price.player,market);const teamId=isH?fixture.teams.home.id:isA?fixture.teams.away.id:h.length>=3?fixture.teams.home.id:a.length>=3?fixture.teams.away.id:null;const samples=teamId===fixture.teams.home.id?h:teamId===fixture.teams.away.id?a:[];const confirmedStarter=lineupConfirmed&&playerInLineup(lineups,price.player),unavailable=injured(injuries,price.player);const line=price.line??((market==='anytime_goal_scorer'||market==='goal_or_assist')?0.5:null);if(line===null)continue;
  let estimate:any;if(market==='anytime_goal_scorer'||market==='goal_or_assist'||market==='player_cards'){const probability=binaryProbability(samples,line);estimate={probability,sampleSize:samples.length,confidence:samples.length>=6?'MEDIA':'BAJA'}}else estimate=estimateOverProbability({samples,line,expectedMinutes:expectedMinutes(samples,confirmedStarter),lineupConfirmed:confirmedStarter});let decision=valueDecision(estimate.probability??null,price.decimalOdds,confirmedStarter);if(unavailable||(lineupConfirmed&&!confirmedStarter))decision={...decision,status:'DESCARTAR'};else if(estimate.confidence==='BAJA'&&decision.status==='VERDE')decision={...decision,status:'AMARILLO'};const needed=Math.max(1,requiredCount(line)),recentForm=samples.slice(0,10).map((s:any)=>({value:s.value,minutes:s.minutes??null,hit:s.value>=needed}));opportunities.push({...price,fixtureId:fixture.fixture.id,teamId,lineupConfirmed,confirmedStarter,unavailable,expectedMinutes:expectedMinutes(samples,confirmedStarter),sampleSize:samples.length,recentForm,estimate,decision});}
 opportunities.sort((a,b)=>(b.decision.edge??-99)-(a.decision.edge??-99));return{matched:true,matchScore:matched.score,fixture:{id:fixture.fixture.id,home:fixture.teams.home.name,away:fixture.teams.away.name},lineupConfirmed,injuriesCount:injuries.length,opportunities};}
